services:
  mysql:
    container_name: lightbuild-mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "lightbuildMySQL"
      MYSQL_DATABASE: lightbuild
      TZ: Asia/Shanghai
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ${DOCKER_VOLUME_DIRECTORY:-.}/mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "exit | mysql -u root -p$$MYSQL_ROOT_PASSWORD"]
      start_period: 30s
      interval: 20s
      timeout: 10s
      retries: 4
    restart: on-failure

  redis:
    container_name: lightbuild-redis
    image: redis:7.0.4
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/data/redis:/data
      - ${DOCKER_VOLUME_DIRECTORY:-.}/redis/redis.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping|grep -e 'PONG\\|NOAUTH'"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure

  neo4j:
    container_name: lightbuild-neo4j
    image: neo4j:5.26.18
    user: root
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      TZ: Asia/Shanghai
      NEO4J_AUTH: "neo4j/lightbuildNeo4j"
      CYPHER_PASSWORD: "lightbuildNeo4j"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/neo4j/data:/data
      - ${DOCKER_VOLUME_DIRECTORY:-.}/neo4j/logs:/logs
      - ${DOCKER_VOLUME_DIRECTORY:-.}/neo4j/import:/var/lib/neo4j/import
    healthcheck:
      test: ["CMD-SHELL", "echo 'RETURN 1' | cypher-shell -a bolt://localhost:7687 -u neo4j -p $$CYPHER_PASSWORD"]
      start_period: 60s
      interval: 20s
      timeout: 10s
      retries: 5
    restart: on-failure

  server:
    container_name: lightbuild-server
    image: openjdk:17-slim
    ports:
      - "9090:9090"
    volumes:
      - ./server/lightbuild-server-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: java -jar /app/app.jar
    environment:
      TZ: Asia/Shanghai
      MYSQL_URL: jdbc:mysql://lightbuild-mysql:3306/lightbuild?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: lightbuildMySQL
      REDIS_HOST: lightbuild-redis
      REDIS_PORT: 6379
      NEO4J_URI: bolt://lightbuild-neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: lightbuildNeo4j
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    restart: on-failure

  web:
    container_name: lightbuild-web
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
    restart: on-failure
